name: Deploy to Firebase Hosting on Staging
'on':
  push:
    branches:
      - staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Firebase JSON File
        env:
          FIREBASE_JSON_STAGING: ${{ secrets.FIREBASE_JSON_STAGING }}
        run: echo $FIREBASE_JSON_STAGING | base64 -di > ./firebase.json
      - uses: actions/checkout@v2
      - run:  npm i --force && npm run build 
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RICH_SUPRSTATE_367315 }}'
          channelId: live
          projectId: rich-suprstate-367315
